name = "Parser"
defaultTargets = ["Parser"]
allowImportAll = true

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.32.0"

[[require]]
name = "UnicodeBasic"
git = "https://github.com/fgdorais/lean4-unicode-basic"
rev = "947120c17904da8fc89abe3616d57e1c3e13aa9c"

[[lean_lib]]
name = "Parser"

[[lean_exe]]
name = "test"
